# Generated by Django 4.2.4 on 2023-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_inviter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
