# Generated by Django 4.2.4 on 2023-08-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0003_profile_my_inviter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
