openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/all_profiles/:
    get:
      operationId: listProfiles
      description: Any Profile Operations for Admin
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
    post:
      operationId: createProfile
      description: Any Profile Operations for Admin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Profile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
  /api/v1/all_profiles/{id}/:
    get:
      operationId: retrieveProfile
      description: Any Profile Operations for Admin
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this Profile.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
    put:
      operationId: updateProfile
      description: Any Profile Operations for Admin
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this Profile.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Profile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateProfile
      description: Any Profile Operations for Admin
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this Profile.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Profile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyProfile
      description: Any Profile Operations for Admin
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this Profile.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/my_profile/:
    get:
      operationId: listProfiles
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
  /api/v1/auth/token/:
    post:
      operationId: createget_jwt_token
      description: Send Token to Confirmed User and Create User if he is new
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/auth/signup/:
    post:
      operationId: createregister
      description: SignUp user and send confirmation code
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/my_profile/{id}/:
    patch:
      operationId: partialUpdateProfile
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Profile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
      tags:
      - api
components:
  schemas:
    Profile:
      type: object
      properties:
        phone:
          type: string
          readOnly: true
          nullable: true
        my_refs:
          type: string
          readOnly: true
        my_inviter:
          type: string
          nullable: true
          maxLength: 50
        my_ref_code:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
